name: Deploy Backend
on:
  push:
    branches:
      - dev  # dev ë¸Œëœì¹˜ì— pushë  ë•Œ ì‹¤í–‰
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Checkout Repository"
      - name: Checkout Repository
        uses: actions/checkout@v3

      - run: echo "Execute remote ssh & deploy back-end server"
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/knit-together-server
            git pull origin dev
            npm install
            npm run dev